### ISSUE TITLE
Gmail IMAP with Oauth2 authentication (doesn't work)

### ISSUE THREAD

**Issue by hamdigdoura** [coddingtonbear/django-mailbox#120]
Gmail IMAP with Oauth2 authentication doesn't work in django 1.9.

 The problem comes from [django-social-auth ](https://github.com/omab/django-social-auth) because it was **deprecated**.

`from social.apps.django_app.default.models import UserSocialAuth`

**Comment by ad-m** [comment]
Is there a workaround? If I good known Gmail support IMAP without OAuth2 too which should be compatibile with standard IMAP backend. See https://support.google.com/mail/answer/7126229?hl=en , but pull requests to fix that are welcome.

**Comment by coddingtonbear** [comment]
@hamdigdoura -- I'm a little confused; it looks like that model still exists in the latest python-social-auth (at least -- as of v0.2.21 which was just released a couple months ago).  I'm curious -- where did you hear that it was deprecated?

**Comment by hamdigdoura** [comment]
@coddingtonbear I got [this error](https://github.com/omab/python-social-auth/issues/1014) in python-social-auth and you can verify that issue is still open.

**Comment by coddingtonbear** [comment]
@hamdigdoura -- just a heads-up, but that message is *not* an error -- it is only a warning, and it is not a deprecation of the library, but a deprecation of a specific feature that that library currently relies upon.  If you are seeing that message and are also encountering a problem using Gmail IMAP with Oauth2, the problem you are experiencing while trying to use Gmail IMAP with Oauth2 is unrelated to that deprecation warning message.

You would be absolutely right that the current version of `python-social-auth` will not work once Django 2.0 is released, but it isn't yet and isn't scheduled for release for more than a year so they have a really long time to sort it out before it affects anybody.

Since it does seem like you're probably encountering a real problem, though, please open another ticket with a detailed description of the problem you're encountering, and one of us will try to help you out!

Cheers!
