### ISSUE TITLE
Specify date to get messages from

### ISSUE THREAD

**Issue by yarnball** [coddingtonbear/django-mailbox#122]
Hi,

Great work on this project :)

I would like to make a small change- to specify which date it pulls messages from. It is a little impractical to fetch every message in a mailbox by default.

Is it possible to set a date from which it gets mail from? Where and how would I set this?

Thanks

**Comment by ad-m** [comment]
@yarnball , there is no way to pull mails on specified time. Email protocols freely treats date messages because of its distributed nature. The process involved a lot of servers, messages are sometimes delayed for a few hours of sending and it would be difficult to give the correct date, so messages can be missing. Is the correct date the date of prepare message, the date of receive by first MTA date, mail of transfer by fourth in order MTA or other?

If you don't want fetch every message in mailbox:

- specify different ```archive``` and ```source``` folder (see http://django-mailbox.readthedocs.io/en/latest/topics/mailbox_types.html#additional-imap-mailbox-features ), 
- specify alias of ```A@example.com``` to ```B@example.com,C@example.com``` and download messages from ```B@example.com``` only.

Greetings,

**Comment by yarnball** [comment]
@ad-m Thanks for the quick reply.

Good to know I can choose a specific folder. 

I think I did not explain well. I want to specify to only get mail AFTER a certain date. Is that still impossible?

Also, is there a version of this that uses the Google gmail API?

**Comment by ad-m** [comment]
GMail OAuth2 has some issues now (#120). GMail IMAP should works freely.

There is no way to fetch (get) mail from server AFTER certain date. You can use ```Message.processed``` field.

**Comment by coddingtonbear** [comment]
I'm afraid there isn't a way for us to only fetch only messages after a specific date, and that might be a little complicated given the problems @ad-m describes above.  What we generally recommend is that one use django-mailbox with dedicated mailboxes only (not mailboxes shared with other tools).

If you bump into more questions about that sort of thing, though, feel free to hop into the [gitter channel](https://gitter.im/coddingtonbear/django-mailbox?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge); I'd be glad to talk one-on-one about it.

Cheers!
