### ISSUE TITLE
Images in email body

### ISSUE THREAD

**Issue by rulzart** [coddingtonbear/django-mailbox#123]
Hi, 

I noticed that images directly in the e-mail body (eg. logos from signatures) are not shown. When I look at the HTML code it looks like this:
`<img width="535" height="420" style="width:5.5729in;height:4.375in" id="Billede_x0020_2" src="cid:image002.jpg@01D22992.3C617670">`

Is it possible to actually put in the real URL from MessageAttachment? Maybe it's obvious and I've overlooked it somehow, but it's been bothering me for some time.

I know this isn't an actual "issue", but more like support :-) Hope to get an answer anyway!

Thanks in advance, 
Jeppe

**Comment by ad-m** [comment]
Hello,

There is currently no support for such images. Feel free to provide pull requests. Do you need assistant to prepare pull requests?

Greetings,

**Comment by coddingtonbear** [comment]
I'm not totally sure that this should be something that django-mailbox does by default, but if you were to post a PR that added a function you could call for transforming the `cid:` links to links to the actual image, I'd totally approve it!

It's probably not _super_ difficult; you could probably get away with just a regex searching for `"cid:[^"]+"` (especially since this is a voluntarily-called method; overmatching is a lot less of a big problem).  If you wanted to get a gold star of special effort, though, you could consider parsing the HTML using lxml (and perhaps just use an xslt to do the transformation?).

Either way, @rulzart -- totally post a pull request for it!  If you do go the route of parsing the HTML, though, hop into the [gitter channel](https://gitter.im/coddingtonbear/django-mailbox?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) and we can talk through some details!

**Comment by rulzart** [comment]
Unfortunately, I do not have too much time on my hands. If I find a satisfying solution I will let you know.

**Comment by rulzart** [comment]
Hi coddington

I managed to create the model property that does this, but it requires a new field on the MessageAttachment model.

I have also added the field "date" to Message for faster sorting by message date. I will make a pull request later today, hopefully.

I have added the following to Message:
field: date (datetimefield)
property: get_cc (gets the Cc addresses from header)
property: html_with_img (replaces cid image values with actual attachment url, requires BeautifulSoup though)

MessageAttachment:
field: cid (charfield, Content-ID from attachment header)

I dunno how you want the fields/functions to be named, but I guess you will give some kind of feedback when I have made a pull request.
