### ISSUE TITLE
Storing original message

### ISSUE THREAD

**Issue by ad-m** [coddingtonbear/django-mailbox#45]
Hello,

During using this package by IMAP transport I observe the message was removed from server after processing. I can reproduce msg file, but with changes in eg. attachment, headers order.

Is there any reason to not add extra model FileField to store original msg file (*.eml) without any changes? I want use data processes by django_mailbox in court, so this is important for me. I know this can produce high capacity usage, so I think about extra settings DJANGO_MAILBOX_STORE_ORIGINAL_MESSAGE .

I can implement that.

**Comment by coddingtonbear** [comment]
That seems reasonable to me as long as:

* `DJANGO_MAILBOX_STORE_ORIGINAL_MESSAGE` is `False` by default.
* When the `DJANGO_MAILBOX_STORE_ORIGINAL_MESSAGE` setting is set to `True`, we continue to store a "dehydrated" message in the current way (so a user changing this value from `True` to `False` will not need to perform a migration).
* (ideally) when the [`get_email_object() method`](https://github.com/coddingtonbear/django-mailbox/blob/master/django_mailbox/models.py#L599) is executed and the message is available on disk (regardless of the `DJANGO_MAILBOX_STORE_ORIGINAL_MESSAGE` setting's value), we construct the message object from the contents of that file rather than rehydrating the message (because the message on disk is always going to be better than the one we rehydrate).
* The documentation is updated to reflect the above change in behavior.

All-in-all, though, I'm not at all opposed.  Previously, we did store the message verbatim, in fact, albeit in a very inefficient way.  Good luck and let me know if you have any questions or need any help!

Cheers,
Adam

**Comment by ad-m** [comment]
Added pull requests to respect this changes ( https://github.com/ad-m/django-mailbox/pull/1 ). I am unable to do it in other way.

**Comment by coddingtonbear** [comment]
This was sorted out as of 4.3.0; fc24cb359565f096b80503628bb3c75fc009a6e4.  Cheers!
