### ISSUE TITLE
Imap, get_message: TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by harlov** [coddingtonbear/django-mailbox#53]
Sometimes, i'm get this error: 

```
Traceback (most recent call last):
  File "/srv/eva/usermonitor-ng/src/usermonitor/reports/tasks.py", line 19, in update_emails
    mb.get_new_mail()
  File "/srv/eva/usermonitor-ng/env/lib/python3.4/site-packages/django_mailbox/models.py", line 373, in get_new_mail
    for message in connection.get_message():
  File "/srv/eva/usermonitor-ng/env/lib/python3.4/site-packages/django_mailbox/transports/imap.py", line 106, in get_message
    message = self.get_email_from_bytes(msg_contents[0][1])
TypeError: 'NoneType' object is not subscriptable
```

Error floating. After repeat task, allright. After repeat income signal, email parsed normaly.

**Comment by coddingtonbear** [comment]
This *should* have been fixed by [these few lines of changes](https://github.com/coddingtonbear/django-mailbox/commit/ff433a24f4c626bbf5ad0f3a7be93a24edf3a3be#diff-c07ae8a8f31a69ac6e3dcc5712f2efbbR109) in the most recent release (4.4).  Let me know if you're still seeing this problem after updating!

**Comment by harlov** [comment]
Oh, i'm understand my error after reading you comment's to this commit (multiple workers read one mailbox ), thank's ))) Updated you package and fixed my code.

But, maybe is better way emit castom exception ( for example ImapConcurrencyException). Because after this commit, user never know about this issue.

**Comment by coddingtonbear** [comment]
It's not really a concurrency *problem*, though, it's just that another
client has deleted this message before we could fetch it.  To clarify: the
only reason we're even seeing this is that we're fetching a listing of
available message IDs in a separate step from where we're downloading the
message; in earlier versions, this wouldn't even be a possibility since we
were essentially just fetching the next-available message.  Either way, the
result is identical: we can/will only process the messages that are there
when we're downloading them.
