### ISSUE TITLE
Work on develop branch

### ISSUE THREAD

**Issue by ad-m** [coddingtonbear/django-mailbox#62]
Hello, 

I am would like ask to work on "develop" branch. It is confusing to see master branch fail. For example I can't verify my pull requests due of that. 

If you have own develop branch you can have this flow:

1. do work on ```develop``` -  ```git checkout develop && git commit -m "foo bar"```
1. merge pull request to ```master``` eg. by web GH interface 
1. do work on ```develop``` branch - ```git checkout develop && git commit -m "foo bar"```
1. get code from pull requests to ```develop``` branch - ```git checkout develop && git merge master```
1. done feature
1. merge to master - ```git checkout master && git merge develop```

I don't think using pull requests by you is necessary, but use own branch will be very nice.

**Comment by coddingtonbear** [comment]
Unfortunately, Github doesn't allow me to grant access to only specific branches.  That being said -- as part of v4.4.4, I added [a change that will allow tests to successfully run when you push up a pull request](https://github.com/coddingtonbear/django-mailbox/commit/c1e3007aa6bd06d56f48d132188920b59fda0cf7), so test running shouldn't be too big of a deal now.

I really do appreciate your offer to help out with the project, though, and will keep it in mind in the future!

**Comment by ad-m** [comment]
I don't mean grant access to specific branches for anyone. I mean don't push non-deployable code on ```master```. I can see commits from @coddingtonbear on ```master``` which fails tests.

I believe tests on ```master``` shouldn't fail, because it is confusing.

**Comment by coddingtonbear** [comment]
Could you elaborate on which tests you see as failing -- [currently they're all passing as far as I can see](https://travis-ci.org/coddingtonbear/django-mailbox)?

There was -- very briefly -- a problem that caused one of the eight builds to fail, but that wasn't because of a test failure, but instead was a problem in which the build process wasn't able to fetch one of the packages it needed.  That sort of thing happens all the time, and I re-kicked-off the build.
