### ISSUE TITLE
Process each messages in invidual transaction

### ISSUE THREAD

**Issue by ad-m** [coddingtonbear/django-mailbox#66]
Hello, 

I am would like suggest add support for transaction - indepent transaction for each messages. Then any exception in message processing, especially signals processign will be safe for database.

In Django many installation use ATOMIC_REQUESTS, so each views (requests) use transaction by default, but in commands you have to add support for transaction handsome.

Greetings,

**Comment by coddingtonbear** [comment]
Sure, that sounds like a great idea!  I'm not so sure about how easy it'll turn out to be though given the way the module is currently architected; do you have any ideas about that?

Specifically, we currently delete each message from the server as we emit it for processing.  Were we to wrap that in a transaction, we would need to make sure that the message is properly processed by each signal handler before deletion, and we thus enter a complex world in which it becomes possible for a signal handler to be executed multiple times for a single message because during previous executions an exception was raised before the transaction could be committed.

Ideas?

**Comment by coddingtonbear** [comment]
Hey there @ad-m; I'm not ever going to have the time to work on such a feature, but if you'd like to submit a patch, you'd definitely win some respect points from me.  For the moment, I'm going to close this ticket, but feel free to submit a PR.

Cheers,
Adam
