### ISSUE TITLE
All incoming email disappeared from original mailbox after consuming by django-mailbox

### ISSUE THREAD

**Issue by cheremovsky** [coddingtonbear/django-mailbox#76]
Hi.

I've just installed django-mailbox app and tried to get the email from my mailbox.
It went just well, I can see all the email in my django-admin but they disappeared\got deleted from my mailbox, it is empty now. I still have out-coming emails, but all income is gone.

Your app looks like really handy one, but (sorry for explicit) wtf!?

**Comment by ad-m** [comment]
> Warning
> Unless you are using IMAP’s ‘Archive’ feature, this will delete any messages it can find in the inbox you specify; do not use an e-mail inbox that you would like to share between applications.

http://django-mailbox.readthedocs.org/en/latest/topics/mailbox_types.html

**Comment by ad-m** [comment]
Personally to achieve backups I have a e-mail alias "addr->inbox,backup". It can be setup easily even in DirectAdmin.

**Comment by cheremovsky** [comment]
Thanks, @ad-m 

I luckily found all the email in the archive and restored it. Also created a mirror email for using django-mailbox. So, problem is solved.

However, in my personal opinion, users might be warned much earlier to avoid unpleasant surprises.

**Comment by ad-m** [comment]
How users can be warned better?

**Comment by cheremovsky** [comment]
For example the warning might be placed right on the installation page http://django-mailbox.readthedocs.org/en/latest/topics/installation.html
alongside with the Note about verifying of configuration.

**Comment by suyashbajpai86** [comment]
The problem is solved for gmail only, In other servers it is persistent even if you specify archive=Archived

**Comment by coddingtonbear** [comment]
That behavior is by design, @suyashbajpai86; all e-mail is consumed and deleted from whatever e-mail inboxes you consume from.  There just happens to also be a feature that allows you to archive processed messages if you happen to be using the IMAP transport.   If you have a project for which you would like to preserve those messages, I'm afraid this library might not be a good match.

**Comment by suyashbajpai86** [comment]
Ok thanks @coddingtonbear for replying; Do you have any idea of any application that can perform that, other than webpymail.

**Comment by coddingtonbear** [comment]
I'm afraid not, @suyashbajpai86, but it sounds like maybe you're trying to build some kind of UI atop an existing mailbox rather than using e-mail for automation.  For that kind of use case, you might find better luck just interacting with the mailbox using Python's built-in libraries for interacting with mailboxes.

That might sound daunting, but it's really not as complicated as it sounds.  I don't know what kinds of mailboxes you're working with, but if you're hoping to build a UI atop an IMAP mailbox, you might find [this article](https://yuji.wordpress.com/2011/06/22/python-imaplib-imap-example-with-gmail/) helpful.  For file-based mailboxes, you can get some insight into what libraries to use, at least, by glancing at the [transports directory](https://github.com/coddingtonbear/django-mailbox/tree/master/django_mailbox/transports) of this project.  If you're hoping to build a UI atop a POP3 mailbox without deleting messages, you're going to have a bad time.

**Comment by suyashbajpai86** [comment]
Thanks for your help @coddingtonbear :)

**Comment by coddingtonbear** [comment]
No problem, @suyashbajpai86 -- good luck!
