### ISSUE TITLE
unhandled exceptions in admin action get_new_mail

### ISSUE THREAD

**Issue by misli** [coddingtonbear/django-mailbox#91]
Exceptions thrown in get_new_mail are not handled.
1. with wrong url format it throws UnboundLocalError "local variable 'conn' referenced before assignment" in django_mailbox/models.py in get_connection, line 255
2. with gmail it throws error "[ALERT] Please log in via your web browser: https://support.google.com/mail/accounts/answer/78754 (Failure)"
I know, that I should use django-social-auth, but the exceptions should be nandled anyway

**Comment by coddingtonbear** [comment]
Sounds totally reasonable to me that we might handle that better in the admin; could you file a pull request adding that handling, @misli?

**Comment by pablodiazgutierrez** [comment]
Was this ever resolved? I'm running into this issue on version 4.5.3 and I wonder if updating to a more recent release would help.

**Comment by coddingtonbear** [comment]
Nope, @pablodiazgutierrez, but if you posted a PR, you could get this one step closer to being fixed.

**Comment by pablodiazgutierrez** [comment]
Thanks @coddingtonbear, I'll give it a try. Unfortunately I'm only getting this error on my production server, which is no playground... :)

**Comment by coddingtonbear** [comment]
Let me know if you need any help; the problem above is mostly one of how an error is reported rather than being about actually fixing the error.  If what you're attempting to fix is the underlying problem, @pablodiazgutierrez, you might just want to just double-check that a proper URI is entered for your mailbox (the first of the above problems), or have a look at your logs to see if you can find an indication of another error (like the second of the above problems).

**Comment by Lifechess** [comment]
this post is old but i'm using django-mailbox 4.8.1 and my problem is admin action get_new_mail not working but from the shell it is working and i don't have any error.

**Comment by pfouque** [comment]
I guess it has been fixed at some point, maybe in [this commit](https://github.com/coddingtonbear/django-mailbox/commit/505bc8d1c906d34af0046fdf84effe051ea4225f).
@Lifechess Could you retry with the newly released 4.9.0?
