### ISSUE TITLE
Message attachments upload path issue

### ISSUE THREAD

**Issue by cheremovsky** [coddingtonbear/django-mailbox#99]
Hello again!

Somehow all the attachments started to be saved literally in 'mailbox_attachments/%Y/%m/%d/' folder instead of 'mailbox_attachments/2016/05/25/' for example.

**Comment by ykoryakov** [comment]
Initial migration executed **get_attachment_save_path** and wrote bytestring to upload_to. Looks like it can be solved by replacing this string with function **django_mailbox.utils.get_attachment_save_path** in new migration.

I have the another problem, but because of the same thing. When I try to set custom DJANGO_MAILBOX_ATTACHMENT_UPLOAD_TO, django migration fails because of finding new upload_to.

**Comment by coddingtonbear** [comment]
Thanks for the heads-up @cheremovsky; I'm a little embarassed to have not caught that earlier!  @ykoryakov & @cheremovsky  -- I think release 4.5.2 should solve both of your problems; there was also a missing (non-schema changing) [migration](https://github.com/coddingtonbear/django-mailbox/pull/98) that was part of this same problem and @WnP submitted a patch fixing that that I've also merged.

**Comment by ykoryakov** [comment]
Thank you for fix, Adam! Works great.
